export * from './Header';
export * from './Layout';
export * from './About';
export * from './Biology';
export * from './Selfhelp';
export * from './Contact';
export * from './Partner';
export * from './Footer';
export * from './Logo';